version: '3.8'
name: setoalt
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

