version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: setoalt-api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - database
    networks:
      setoalt-network:

  ui:
    build:
      context: ./ui
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: setoalt-ui
    ports:
      - "80:80"
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api
    networks:
      setoalt-network:

  database:
    image: postgres:14
    container_name: setoalt-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./database/scripts/insert-data.sql:/docker-entrypoint-initdb.d/insert-data.sql
    restart: always
    networks:
      setoalt-network:

volumes:
  postgres-data:

networks:
  setoalt-network:
