CREATE USER app_user WITH PASSWORD 'app_password'; -- should match values DB_USER and DB_PASSWORD in .env

GRANT CONNECT ON DATABASE setoalt TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;
GRANT CREATE, SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
