export enum ShortKey {
    MICRO_TUNING = "M",
    CHANGE_TYPE = "T",
    SHIFT_LEFT = "B",
    SHIFT_RIGHT = "N",
    DELETE_NOTE = "DELETE",
    REMOVE_NOTE = "BACKSPACE",
    DIVIDER = "D",
    BREAK = "ENTER",
    HALF_NOTE = "Q",
    QUARTER_NOTE = "W",
    EIGHT_NOTE = "E",
    INCREASE_PITCH = "ARROWUP",
    DECREASE_PITCH = "ARROWDOWN",
    START_PLAYBACK = " ",
    PREVIOUS = "ARROWLEFT",
    NEXT = "ARROWRIGHT",
    UNDO = "Z",
    REDO = "Y",
}
